
export const tasks = [
    {
        title: "Build react app",
        dueDate: "8:00:00 AM",
        notes: "Use secure coding practice",
        description: "Ensure all functionality are displayed correctly",
        checklist: "",
    },
    {
        title: "Prepare project report",
        dueDate: "9:00:00 AM",
        notes: "Include all recent updates",
        description: "Compile data and write report summary",
        checklist: "",
    },
    {
        title: "Team meeting",
        dueDate: "10:00:00 AM",
        notes: "Discuss project milestones",
        description: "Review progress and plan next steps",
        checklist: "",
    },
    {
        title: "Code review",
        dueDate: "11:00:00 AM",
        notes: "Focus on security and performance",
        description: "Review team members' code submissions",
        checklist: "",
    },
    {
        title: "Client call",
        dueDate: "12:00:00 PM",
        notes: "Prepare questions and updates",
        description: "Discuss project requirements and feedback",
        checklist: "",
    },
    {
        title: "Lunch break",
        dueDate: "1:00:00 PM",
        notes: "Relax and recharge",
        description: "Take a break from work",
        checklist: "",
    },
    {
        title: "Write unit tests",
        dueDate: "2:00:00 PM",
        notes: "Cover all edge cases",
        description: "Ensure code reliability with tests",
        checklist: "",
    },
    {
        title: "Design new feature",
        dueDate: "3:00:00 PM",
        notes: "Follow design guidelines",
        description: "Create wireframes and prototypes",
        checklist: "",
    },
    {
        title: "Update documentation",
        dueDate: "4:00:00 PM",
        notes: "Reflect recent changes",
        description: "Update project documentation",
        checklist: "",
    },
    {
        title: "Deploy app",
        dueDate: "5:00:00 PM",
        notes: "Monitor for issues",
        description: "Deploy new version to production",
        checklist: "",
    },
    {
        title: "Follow up with support team",
        dueDate: "6:00:00 PM",
        notes: "Check on ongoing issues",
        description: "Ensure customer tickets are resolved",
        checklist: "",
    },
    {
        title: "Research new tools",
        dueDate: "7:00:00 PM",
        notes: "Evaluate benefits",
        description: "Look into new tools for team productivity",
        checklist: "",
    },
    {
        title: "Review analytics",
        dueDate: "8:00:00 PM",
        notes: "Identify trends",
        description: "Analyze user engagement and performance metrics",
        checklist: "",
    },
    {
        title: "Plan next sprint",
        dueDate: "9:00:00 PM",
        notes: "Prioritize tasks",
        description: "Outline goals and tasks for the upcoming sprint",
        checklist: "",
    },
    {
        title: "Team building activity",
        dueDate: "10:00:00 AM",
        notes: "Foster team spirit",
        description: "Engage in team-building exercises",
        checklist: "",
    },
    {
        title: "Conduct interview",
        dueDate: "11:00:00 AM",
        notes: "Assess technical skills",
        description: "Interview candidate for open position",
        checklist: "",
    },
    {
        title: "Security audit",
        dueDate: "12:00:00 PM",
        notes: "Check for vulnerabilities",
        description: "Conduct a security audit of the application",
        checklist: "",
    },
    {
        title: "Refactor legacy code",
        dueDate: "1:00:00 PM",
        notes: "Improve code quality",
        description: "Update and optimize old code",
        checklist: "",
    },
    {
        title: "Attend webinar",
        dueDate: "2:00:00 PM",
        notes: "Learn about new trends",
        description: "Participate in industry webinar",
        checklist: "",
    },
    {
        title: "Backup database",
        dueDate: "3:00:00 PM",
        notes: "Ensure data safety",
        description: "Perform regular database backup",
        checklist: "",
    },
    {
        title: "Optimize performance",
        dueDate: "4:00:00 PM",
        notes: "Reduce load times",
        description: "Optimize app for better performance",
        checklist: "",
    },
];
