
export const tasks = [
    {
        description: "Implement the initial structure and basic components",
        dueDate: "7/7/2024, 3:22:00 AM",
        notes: "Focus on creating a solid foundation",
        priority: "1",
        title: "Build react app",
        checklist: "Work",
    },
    {
        description: "Design the main user interface",
        dueDate: "7/7/2024, 3:22:00 AM",
        notes: "Ensure UI is intuitive and user-friendly",
        priority: "2",
        title: "Design UI",
        checklist: "Work",
    },
    {
        description: "Integrate API for data fetching",
        dueDate: "7/9/2024, 3:22:00 AM",
        notes: "Secure and efficient API integration",
        priority: "1",
        title: "Integrate API",
        checklist: "Work",
    },
    {
        description: "Write unit tests for components",
        dueDate: "7/9/2024, 3:22:00 AM",
        notes: "Cover all possible edge cases",
        priority: "2",
        title: "Write unit tests",
        checklist: "Work",
    },
    {
        description: "Deploy the application to production",
        dueDate: "8/9/2024, 3:22:00 AM",
        notes: "Monitor deployment for any issues",
        priority: "1",
        title: "Deploy app",
        checklist: "Work",
    },
    {
        description: "Conduct a code review session",
        dueDate: "7/7/2025, 3:22:00 AM",
        notes: "Focus on code quality and best practices",
        priority: "2",
        title: "Code review",
        checklist: "Work",
    },
    {
        description: "Visit Taipei",
        dueDate: "7/15/2024, 8:00:00 AM",
        notes: "Enjoy life while it lasts",
        priority: "3",
        title: "Tourism",
        checklist: "Personal",
    },
];
